EXP: 'weibo-debug-testsampling-after-constant-ones-newplot-nocluster'
VIS_FILTERS: True
VIS_CONCENTRATION: False
VIS_LOSS: True
DEVICE: 'cuda'

DATASET:
    NAME: 'weibo_'
    DATADIR: 'batch_data'
    LABEL_TYPE: 'amnet-filter-full'
    BATCH_SIZE: 0
    BATCH_TYPE: 'edge'
    K: 5
    LABEL_IDX: None
  
MODEL:
    NAME: 'multi-scale-amnet'
    RECONS: 'struct'
    D: 5
    EPOCH: 2
    HIDDEN_DIM: 128
    LR: 1e-3
    DEBUG: True
    SAMPLE_TRAIN: True
    SAMPLE_TEST: True
    ALPHA: 0.

DETECTION:
    TYPE: 'mean'