EXP: 'weibo-allscs3-oneclust-fixedges-sc2-500e-dominant-nodesamp'
DEVICE: 'cuda'

DATASET:
    NAME: 'weibo'
    DATADIR: 'batch_data'
    LABEL_TYPE: 'single'
    BATCH_SIZE: 0
    BATCH_TYPE: 'edge'
    K: 1
    LABEL_IDX: None
    SCALES: 3
  
MODEL:
    NAME: 'dominant'
    RECONS: 'struct'
    IND: 1
    CONTRASTIVE: True
    SCALES: 1
    D: 3
    K: 3
    EPOCH: 500
    HIDDEN_DIM: 128
    LR: 1e-4
    DEBUG: True
    SAMPLE_TRAIN: True
    SAMPLE_TEST: True
    ALPHA: 0.

DETECTION:
    TYPE: 'mean'

VIS:
    VIS_FILTERS: False
    VIS_CONCENTRATION: False
    VIS_LOSS: True
    SAVE_SPECTRUM: False