EXP: 'weibos-sc3-newanom'
SCALES: 1
DEVICE: 'cuda'

DATASET:
    NAME: 'weibo'
    DATADIR: 'batch_data'
    LABEL_TYPE: 'single'
    BATCH_SIZE: 0
    BATCH_TYPE: 'edge'
    K: 1
    LABEL_IDX: None
    CLUST_IND: 3
  
MODEL:
    NAME: 'multi-scale-amnet'
    RECONS: 'struct'
    CONTRASTIVE: True
    D: 5
    K: 5
    EPOCH: 150
    HIDDEN_DIM: 128
    LR: 1e-4
    DEBUG: True
    SAMPLE_TRAIN: True
    SAMPLE_TEST: True
    ALPHA: 0.

DETECTION:
    TYPE: 'mean'

VIS:
    VIS_FILTERS: False
    VIS_CONCENTRATION: False
    VIS_LOSS: True
    SAVE_SPECTRUM: False