EXP: 'yelpchi-newrank'
DEVICE: 'cuda'

DATASET:
    NAME: 'yelpchi'
    DATADIR: 'batch_data'
    LABEL_TYPE: 'single'
    BATCH_SIZE: 5
    BATCH_TYPE: 'edge'
    K: 1
    SCALES: 3
    NUM_NEIGHBORS_SAMP: 10
  
MODEL:
    IND: None
    NAME: 'multi-scale-dominant'
    RECONS: 'struct'
    SCALES: 3
    D: 3
    K: 3
    EPOCH: 1000
    HIDDEN_DIM: 128
    LR: 1e-4
    DEBUG: True
    SAMPLE_TRAIN: True
    SAMPLE_TEST: True